### ISSUE TITLE
Add Placeholder Text for Text Area Questions

### ISSUE THREAD

**Issue by benfarahmand** [TuvaLabs/markdown-delight-editor#5]
Let's add space for placeholder text. The text would appear in light grey in the text area and would disappear once the student starts writing. This can be useful for adding sentence starters or various hints.

Here's example format:
?[question_id][ACTUAL_QUESTION]=_ [PLACEHOLDER_TEXT]

?[question_id][ACTUAL_QUESTION]=__ [PLACEHOLDER_TEXT]

?[question_id][ACTUAL_QUESTION]=___ [PLACEHOLDER_TEXT]

**Comment by naveenkumarganesan** [comment]
Closing this since it is not a part of this repo.
